
version: '3.8'
services:
  sqludemy:
    image: mysql:8.0
    hostname: sqsqludemyl
    container_name: sqludemy
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=udemyspring
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    ports:
      - '3306:3306'
#    volumes:
#      - db:/var/lib/mysql
#      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
#volumes:
#  db:
#    driver: local