management:
  endpoints.web.exposure.include: "*"
  info.env.enabled: true

info:
  app:
    name: My Super Cool App
    description: A crazy fun app, yoohoo!
    version: 1.0.0

spring:
  security:
    user:
      name: Denzel
      password: fuckoff

#
# Define my custom crazy properties
#

coach:
  name: Mickey Mouse

team:
  name: The Mouse Club